void load_file();
void select_screen();
void ProgramEnd();
void Admin();
// void User();
void location_manage_select();
void location_manage_add();
void location_manage_edit();
void spot_manage(int select);
void spot_add(int select_LocNum, int select_RoomNum);
void spot_edit(int select_LocNum, int select_RoomNum);
void printEOF();
int isCancel(char* str);
void flush();
void outOfInput();